# Generated by Django 3.1.7 on 2021-02-27 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eclapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountheads',
            options={},
        ),
        migrations.AlterModelOptions(
            name='accountname',
            options={},
        ),
        migrations.AlterModelOptions(
            name='accounttype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='journallog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='journallogdetails',
            options={},
        ),
        migrations.AlterField(
            model_name='accountname',
            name='type_of_acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclapp.accounttype'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='acc_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclapp.accountheads'),
        ),
        migrations.AlterField(
            model_name='journallogdetails',
            name='account_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclapp.accountname'),
        ),
        migrations.AlterField(
            model_name='journallogdetails',
            name='journal_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclapp.journallog'),
        ),
        migrations.AlterModelTable(
            name='accountheads',
            table=None,
        ),
        migrations.AlterModelTable(
            name='accountname',
            table=None,
        ),
        migrations.AlterModelTable(
            name='accounttype',
            table=None,
        ),
        migrations.AlterModelTable(
            name='journallog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='journallogdetails',
            table=None,
        ),
    ]
